# -*- coding: utf-8 -*-
"""NBSVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMe2hMrTVw-weAoSTiJTNMoScFFl70Tm
"""

# [셀 0] KoNLPy 설치
!pip install konlpy

# ==========================================
# [셀 1] 환경 설정 및 구글 드라이브 연동
# ==========================================
import os
import sys
import numpy as np
import pandas as pd
import joblib
from scipy.sparse import hstack, csr_matrix
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# 코랩 구글 드라이브 마운트 (파일 영구 저장을 위함)
try:
    from google.colab import drive
    drive.mount('/content/drive')
    # 구글 드라이브 내 'fake_news_project' 폴더를 기본 경로로 설정
    BASE_PATH = "/content/drive/MyDrive/fake_news_project"
    os.makedirs(BASE_PATH, exist_ok=True)
    print(f"\n✅ 구글 드라이브 마운트 성공!\n📂 작업 경로: {BASE_PATH}")
    print(f"💡 주의: 구글 드라이브 '{BASE_PATH}' 폴더 안에 'subset_01.csv' 파일을 업로드해 주세요!")
except ImportError:
    BASE_PATH = os.path.dirname(os.path.abspath(__file__)) if '__file__' in locals() else os.getcwd()
    print(f"⚠️ 코랩 환경이 아닙니다. 로컬 경로를 사용합니다: {BASE_PATH}")

# ==========================================
# [셀 2] 환경 설정, 형태소 분석기 초기화 및 NBSVM 함수
# ==========================================
import os
import sys
import numpy as np
import pandas as pd
import joblib
from scipy.sparse import hstack, csr_matrix
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from konlpy.tag import Okt

try:
    from google.colab import drive
    if not os.path.ismount('/content/drive'):
        drive.mount('/content/drive')
    BASE_PATH = "/content/drive/MyDrive/fake_news_project"
    os.makedirs(BASE_PATH, exist_ok=True)
except ImportError:
    BASE_PATH = os.getcwd()

okt = Okt()

STOPWORDS = set(['하다', '있다', '되다', '이다', '않다', '그렇다', '아니다', '이렇다', '그', '이',
                 '저', '것', '수', '등', '들', '및', '에서', '그리고', '그래서', '기자', '뉴스', '보도', '밝히다'])

def okt_tokenizer(text):
    tokens = []
    for word, pos in okt.pos(text, stem=True):
        if pos in ['Noun', 'Adjective', 'Verb'] and word not in STOPWORDS and len(word) > 1:
            tokens.append(word)
    return tokens

def extract_dvl_features(df, text_col='content'):
    title_str = df['title'].astype(str)
    content_str = df[text_col].astype(str)
    title_len, content_len = title_str.str.len(), content_str.str.len()

    pattern = '결국|충격|경악|속보|단독|논란|분노|의혹|발각|공개|주의|확인'
    emo_count = title_str.str.count(pattern)
    emo_ratio = emo_count / (title_len + 1)
    quote_count = content_str.str.count(r'["\']')
    quote_ratio = quote_count / (content_len + 1)
    ellipsis_count = title_str.str.count(r'\.\.\.')
    ellipsis_ratio = ellipsis_count / (title_len + 1)
    excl_count = title_str.str.count('!') + content_str.str.count('!')
    excl_ratio = excl_count / (title_len + content_len + 1)
    quest_count = title_str.str.count(r'\?') + content_str.str.count(r'\?')
    quest_ratio = quest_count / (title_len + content_len + 1)

    return pd.DataFrame({
        'emo_count': emo_count, 'emo_ratio': emo_ratio,
        'quote_count': quote_count, 'quote_ratio': quote_ratio,
        'ellipsis_count': ellipsis_count, 'ellipsis_ratio': ellipsis_ratio,
        'excl_count': excl_count, 'excl_ratio': excl_ratio,
        'quest_count': quest_count, 'quest_ratio': quest_ratio,
        'title_len': title_len, 'content_len': content_len
    })

def compute_nb_ratio(X, y, alpha=1.0):
    y = np.array(y)
    p = np.asarray(X[y == 1].sum(axis=0)).flatten() + alpha
    q = np.asarray(X[y == 0].sum(axis=0)).flatten() + alpha
    r = np.log((p / p.sum()) / (q / q.sum()))
    return r

# ==========================================
# [셀 3] 모델 훈련 (0.8 돌파: Chi-Square 통계 선택 + NBSVM)
# ==========================================
from sklearn.feature_selection import SelectKBest, chi2

def train_model(path):
    train_filename = os.path.join(path, "subset_01.csv")
    if not os.path.exists(train_filename): return print("🚨 훈련 데이터 없음!")

    total_df = pd.read_csv(train_filename, usecols=['title', 'content', 'label']).dropna()
    y = total_df['label'].astype(int)

    train_df, test_df, y_train, y_test = train_test_split(total_df, y, test_size=0.2, random_state=42, stratify=y)

    # 제목 가중치 5배 증폭
    X_train_text = (train_df['title'].astype(str) + " ") * 5 + train_df['content'].astype(str)
    X_test_text = (test_df['title'].astype(str) + " ") * 5 + test_df['content'].astype(str)

    print("\n⏳ 1. 초정밀 통계 기반 텍스트 분석 중... (커피 한잔하며 약 5~10분 대기 ☕)")

    # 🔥 비법 1: 피처 상한선을 5~6만 개로 대폭 해제 (숨은 단어 포집)
    print("  -> 형태소 분석 중 (단어 단위 최대 6만개)...")
    tfidf_word = TfidfVectorizer(
        tokenizer=okt_tokenizer, token_pattern=None,
        ngram_range=(1, 2), max_features=60000, sublinear_tf=True, min_df=3
    )
    X_tr_word = tfidf_word.fit_transform(X_train_text)
    X_te_word = tfidf_word.transform(X_test_text)

    print("  -> 글자 패턴 분석 중 (자음/모음 단위 최대 6만개)...")
    tfidf_char = TfidfVectorizer(
        analyzer='char_wb', ngram_range=(2, 4),
        max_features=60000, sublinear_tf=True, min_df=3
    )
    X_tr_char = tfidf_char.fit_transform(X_train_text)
    X_te_char = tfidf_char.transform(X_test_text)

    # 일단 모든 피처를 합침 (약 10만 ~ 12만 차원의 거대 행렬)
    X_tr_massive = hstack([X_tr_word, X_tr_char]).tocsr()
    X_te_massive = hstack([X_te_word, X_te_char]).tocsr()

    # 🔥 비법 2: 카이제곱(Chi-Square) 통계 검정으로 '진짜 쓸모있는' 40,000개만 정밀 추출
    print("🧲 1.5. 카이제곱(Chi-Square) 검정으로 최상위 진성 피처 추출 중...")
    selector = SelectKBest(chi2, k=40000)
    X_tr_selected = selector.fit_transform(X_tr_massive, y_train)
    X_te_selected = selector.transform(X_te_massive)

    # 🔥 비법 3: 정제된 피처에 NBSVM 가중치 부여 (성능 극대화)
    print("🧠 1.8. 순도 100% 피처에 NBSVM (Log-count Ratio) 가중치 적용 중...")
    r_vector = compute_nb_ratio(X_tr_selected, y_train)
    X_tr_tfidf = X_tr_selected.multiply(r_vector).tocsr()
    X_te_tfidf = X_te_selected.multiply(r_vector).tocsr()

    print("🧩 2. 메타 패턴 추출 및 스케일링 중...")
    train_meta_df, test_meta_df = extract_dvl_features(train_df), extract_dvl_features(test_df)

    scaler = StandardScaler()
    train_meta_scaled = scaler.fit_transform(train_meta_df)
    test_meta_scaled = scaler.transform(test_meta_df)

    X_train_combined = hstack([X_tr_tfidf, csr_matrix(train_meta_scaled)]).tocsr()
    X_test_combined = hstack([X_te_tfidf, csr_matrix(test_meta_scaled)]).tocsr()

    # 정제된 데이터이므로 C값을 과감하게 올려서 디테일한 경계선을 찾음
    C_candidates = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    best_cv_f1, best_C = 0, 0

    print(f"\n🎯 [하이퍼파라미터 교차 검증 시작 (L2 Ridge Penalty)]")
    for C_val in C_candidates:
        cv_f1, cv_acc = [], []
        for train_idx, val_idx in skf.split(X_train_combined, y_train):
            X_tr, X_val = X_train_combined[train_idx], X_train_combined[val_idx]
            y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

            model = LinearSVC(penalty='l2', C=C_val, class_weight='balanced', random_state=42, max_iter=5000, dual=False)
            model.fit(X_tr, y_tr)
            preds = model.predict(X_val)
            _, _, f1, _ = precision_recall_fscore_support(y_val, preds, average='macro', zero_division=0)
            cv_f1.append(f1); cv_acc.append(accuracy_score(y_val, preds))

        print(f"🔹 [C={C_val:<4}] 검증 정확도: {np.mean(cv_acc):.4f} | 검증 F1-Score: {np.mean(cv_f1):.4f}")
        if np.mean(cv_f1) > best_cv_f1: best_cv_f1, best_C = np.mean(cv_f1), C_val

    print(f"\n🚀 최종 모델 학습 (최적 C = {best_C}) 및 최적 임계값 탐색 중...")
    final_model = LinearSVC(penalty='l2', C=best_C, class_weight='balanced', random_state=42, max_iter=5000, dual=False)
    final_model.fit(X_train_combined, y_train)

    decision_scores = final_model.decision_function(X_test_combined)
    best_threshold, best_f1_thresh = 0, 0

    # 기준선 정밀 튜닝
    for thresh in np.arange(-1.0, 1.0, 0.05):
        temp_pred = (decision_scores > thresh).astype(int)
        _, _, temp_f1, _ = precision_recall_fscore_support(y_test, temp_pred, average='macro', zero_division=0)
        if temp_f1 > best_f1_thresh:
            best_f1_thresh, best_threshold = temp_f1, thresh

    y_pred_optimal = (decision_scores > best_threshold).astype(int)
    _, _, final_f1, _ = precision_recall_fscore_support(y_test, y_pred_optimal, average='macro', zero_division=0)

    print(f"\n📊 [최종 독립 테스트 결과 (순수 단일 모델 극한 테스트)]")
    print(f"🔥 최적 결정 임계값: {best_threshold:.2f}")
    print(f"🔥 최종 F1-Score: {final_f1:.4f} 🚀 (카이제곱 피처 선택 + 하이브리드 NBSVM 적용)")

    # 예측 모드를 위한 저장 (selector가 추가됨)
    joblib.dump(best_threshold, os.path.join(path, 'best_threshold_svm.pkl'))
    joblib.dump(scaler, os.path.join(path, 'best_scaler_svm.pkl'))
    joblib.dump(final_model, os.path.join(path, 'best_model_svm.pkl'))
    joblib.dump(r_vector, os.path.join(path, 'best_nb_r_vector.pkl'))
    joblib.dump(tfidf_word, os.path.join(path, 'best_vec_word.pkl'))
    joblib.dump(tfidf_char, os.path.join(path, 'best_vec_char.pkl'))
    joblib.dump(selector, os.path.join(path, 'best_selector.pkl')) # 🔥 Feature Selector 저장
    print("🌟 0.8 돌파용 최적화 모델 및 각종 변수 저장 완료!")

# ==========================================
# [셀 4] 예측 모드 (Chi-Square 로드)
# ==========================================
def predict_news(path):
    crawl_filename = os.path.join(path, "realtime_news.csv")
    if not os.path.exists(crawl_filename): return print("🚨 크롤링 데이터 없음!")

    crawl_df = pd.read_csv(crawl_filename)
    try:
        scaler = joblib.load(os.path.join(path, 'best_scaler_svm.pkl'))
        model = joblib.load(os.path.join(path, 'best_model_svm.pkl'))
        best_threshold = joblib.load(os.path.join(path, 'best_threshold_svm.pkl'))
        r_vector = joblib.load(os.path.join(path, 'best_nb_r_vector.pkl'))
        tfidf_word = joblib.load(os.path.join(path, 'best_vec_word.pkl'))
        tfidf_char = joblib.load(os.path.join(path, 'best_vec_char.pkl'))
        selector = joblib.load(os.path.join(path, 'best_selector.pkl')) # 🔥 Feature Selector 로드
    except Exception as e: return print(f"🚨 파일 로드 실패! 훈련을 먼저 진행해주세요.\n에러: {e}")

    text_col = 'clean_message' if 'clean_message' in crawl_df.columns else 'text'
    X_real_text = (crawl_df['title'].fillna("").astype(str) + " ") * 5 + crawl_df[text_col].fillna("").astype(str)

    print("🔄 1. 실전 기사 거대 피처 변환 중...")
    X_real_word = tfidf_word.transform(X_real_text)
    X_real_char = tfidf_char.transform(X_real_text)
    X_real_massive = hstack([X_real_word, X_real_char]).tocsr()

    print("🧲 2. 카이제곱(Chi-Square) 필터링 및 NBSVM 가중치 적용 중...")
    # 훈련 때 골라둔 40,000개의 진성 피처만 뽑아냄
    X_real_selected = selector.transform(X_real_massive)
    X_real_tfidf = X_real_selected.multiply(r_vector).tocsr()

    print("🧩 3. 메타 패턴 추출 및 스케일링 중...")
    real_meta_scaled = scaler.transform(extract_dvl_features(crawl_df))
    X_real_combined = hstack([X_real_tfidf, csr_matrix(real_meta_scaled)]).tocsr()

    print("🎯 판별 진행 중...")
    decision_scores = model.decision_function(X_real_combined)

    crawl_df['predicted_label'] = (decision_scores > best_threshold).astype(int)
    probs = 1 / (1 + np.exp(-decision_scores))
    crawl_df['fake_probability(%)'] = np.round(probs * 100, 2)
    crawl_df['결과_텍스트'] = crawl_df['predicted_label'].map({0: '✅ 진짜뉴스', 1: '🚨 가짜뉴스'})

    out_file = os.path.join(path, "realtime_news_svm_result.csv")
    crawl_df.to_csv(out_file, index=False, encoding='utf-8-sig')
    print(f"🎉 판별 완료! 결과: {os.path.basename(out_file)}")

# ==========================================
# [셀 5] 메인 UI
# ==========================================
while True:
    print("\n" + "#"*45 + "\n📰 가짜뉴스 판별 시스템 (NBSVM 하이퍼파라미터 최적화)\n" + "#"*45)
    choice = input("1. 훈련 모드 | 2. 예측 모드 | 3. 종료 ▶️ ")
    if choice == '1': train_model(BASE_PATH)
    elif choice == '2': predict_news(BASE_PATH)
    elif choice == '3': break